#undef DEBOUNCE
#define DEBOUNCE 35

#undef TAPPING_TERM
#define TAPPING_TERM 193

#define COMBO_TERM 100

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 125

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 3

#define AUTO_SHIFT_TIMEOUT 165
#define SERIAL_NUMBER "ndVrG/m5q5Rj"
#define LAYER_STATE_32BIT
#define COMBO_COUNT 26

#define TAPPING_TERM_PER_KEY
